name: Formatting Code

on:
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - uses: actions/checkout@v2 # Check out the repository first.
            - uses: actionsx/prettier@v2
              with:
                    # prettier CLI arguments.
                    args: --write .

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Formatted code
                  branch: ${{ github.head_ref }}
